packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - msgpackr-extract
  - unrs-resolver
allowBuilds:
  '@whiskeysockets/baileys': true
  msgpackr-extract: true
  protobufjs: true
  unrs-resolver: true
